=== NGazzilli/Adisys_Git/system_files/entity_dao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="daoClass">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="entity"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="dao"/>
      </xs:sequence>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dao" type="xs:string"/>
</xs:schema>

=== NGazzilli/Adisys_Git/system_files/entity_dao.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
Questo file contiene i dati necessari alla navigazione dal nome della entity alla DAO associata.
Viene usato dalle Entity per capire la DAO a cui sono associate.
NB: il nome deve essere completo di tutti i package e sotto package
-->
<daoClass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:noNamespaceSchemaLocation="entity_dao.xsd">

	<entity name="Patologia">
		<dao>integration.dao.PatologiaMySqlDAO</dao>
	</entity>

	<entity name="Paziente">
		<dao>integration.dao.PazienteMySqlDAO</dao>
	</entity>
	
	<entity name="Infermiere">
		<dao>integration.dao.InfermiereMySqlDAO</dao>
	</entity>
	
	<!-- Usato per la entity Intervento -->
	<entity name="Intervento">
		<dao>integration.dao.InterventoMySqlDAO</dao>
	</entity>
s
</daoClass>
